### ISSUE TITLE
Not all tasks are visible

### ISSUE THREAD

**Issue by super-ben** [DCsunset/taskwarrior-webui#53]
Hi,

I noticed this earlier but didn't tinker with it very much. Now as the webui works with iOS I tried again so it is a bit bigger deal for me. :) 

The actual problem is:
- when I set up and start the container, I can see less tasks on the webui than in my actual taskwarrior cli (currently 40 in cli vs. 31 in the webui)

My current docker-compose file:

```
version: '3.7'
services:
  taskwarrior-webui:
    image: dcsunset/taskwarrior-webui:latest
    container_name: taskwarrior-webui
    volumes:
      - $HOME/.taskrc:/.taskrc
      - $HOME/.task:/.task
      - /usr/share/taskwarrior/holidays.hu-HU.rc:/usr/share/taskwarrior/holidays.hu-HU.rc
    ports:
      - 5678:80
    restart: always
```
Any ideas, what am I doing wrong?

Bonus question, if I may: this way, I can see the tasks, but cannot sync, as it (rightly) doesn't find the CA under /.task, but when I mount it differently, say, `- $HOME/.taskrc:/home/user/.taskrc` (and .task similarly), the tasks don't appear on the webui. I'm pretty sure this is something simple but can't seem to see it.

**Comment by DCsunset** [comment]
Hi, can you try running taskwarrior cli inside the container to get some output? You can also try running sync command to see if there's a problem.

**Comment by super-ben** [comment]
Thank you for your answer and the tips. The current sutuation is 37 tasks on the cli and 32 on the webui in the browser. When I take a look at the container, it gets interesting, as it shows 37 tasks.

When I run a sync, I see the CA certificate error mentioned:

```shell
docker exec -it taskwarrior-webui sh
/ # task synchronize
TASKRC override: /.taskrc
TASKDATA override: /.task
CA certificate not found.
```

When I run a simple `task` command, the override message is also shown. What am I doing wrong?

When I reconfigure the compose file and mount it to `/home/myuser/.task` and `/home/myuser/.taskrc`, the webui doesn't show a thing, and when I look at the container I see this:

```shell
/ # task
TASKRC override: /.taskrc
TASKDATA override: /.task
No matches.
/ # task synchronize
TASKRC override: /.taskrc
TASKDATA override: /.task
Taskserver is not configured.
```

**Comment by super-ben** [comment]
Another update:
If I set up the container like this, the sync works:

```yaml
version: '3.7'
services:
  taskwarrior-webui:
    image: dcsunset/taskwarrior-webui
    container_name: taskwarrior-webui
    volumes:
      - $HOME/.taskrc:/$HOME/.taskrc
      - $HOME/.task:/$HOME/.task
    ports:
      - 5678:80
    restart: always
```
And if I talk a look at the container I see:
```shell
/ # task sync
TASKRC override: /.taskrc
TASKDATA override: /.task
Syncing with server.tld:53589

Sync successful.  No changes.
```
But the gap is still there:
```shell
docker exec -it taskwarrior-webui sh
/ # task
TASKRC override: /.taskrc
TASKDATA override: /.task
...
37 tasks
```
So this is correct, in fact I do have 37 pendig tasks, though on the webui I currently see 31. I'd really like to figure this one out but can't put my finger on it so I'd be grateful for any further ideas (from anyone).

**Comment by DCsunset** [comment]
Thanks for your feedback. I already know why the certificate file doesn't work, but still have no clues on the wrong number of tasks. I'll try to fix the former issue first.

**Comment by super-ben** [comment]
Great, thank you!

**Comment by DCsunset** [comment]
Hi, I think this issue should already be fixed in the latest version. You can set TASKRC and TASKDATA environment variables so that you can mount the config anywhere.

You can also check if this fixes the wrong number of tasks.

**Comment by super-ben** [comment]
Thank you for your efforts! I just tried and unfortunately I see the same results. At this point I tend to think that I'm doing something wrong:
- when I enter the container and run the usual commands:

```shell
/ # task sync
TASKRC override: /.taskrc
TASKDATA override: /.task
CA certificate not found.
/ # task
TASKRC override: /.taskrc
TASKDATA override: /.task
...
26 tasks
```
- while on the web interface I see 21 actual tasks (26 is the correct one)
- just to make sure, I checked and I'm using the latest image indeed:
```shell
docker images |grep task
dcsunset/taskwarrior-webui   latest        b468bdb1c85d   3 hours ago    375MB
```

I didn't change a thing, everything is as in my opening post. I'm really grateful, though, and also out of ideas. If you could give me any pointers, I'll follow them. :)

**Comment by DCsunset** [comment]
Could you show me your command to start the container? You can also run `echo $TASKRC` inside the container to check if the environment variables are set correctly..

**Comment by super-ben** [comment]
Sure thing, as I'm using the docker-compose file shown above, with a simple `docker-compose up -d` command.

**Comment by DCsunset** [comment]
I see. You'll need to override TASKRC and TASKDATA yourself if you want to mount them to a different location. This is because the container doesn't know your username and thus the default path is not the same as your host machine.

You can follow the new document (Configuration part) to set the env variables correctly.

**Comment by super-ben** [comment]
It may not be entirely correct, let me show you why, here's my modified compose file with very direct mapping among the environment variables:

```yaml
version: '3.7'
services:
  taskwarrior-webui:
    image: dcsunset/taskwarrior-webui:latest
    container_name: taskwarrior-webui
    volumes:
      - /home/username/.taskrc:/home/username/.taskrc
      - /home/username/.task:/home/username/.task
    ports:
      - 5678:80
    restart: always
```
And it still doesn't see a thing and tries to override:

```shell
docker exec -it taskwarrior-webui sh
/ # task
TASKRC override: /.taskrc
TASKDATA override: /.task
No matches.
Recently upgraded to 2.6.0. Please run 'task news' to read highlights about the new release.
/ # task sync
TASKRC override: /.taskrc
TASKDATA override: /.task
Taskserver is not configured.
```
However, when I take a look inside, the mapping is correct:

```shell
docker exec -it taskwarrior-webui sh
/ # ls -hal /home/username/
total 16K    
drwxr-xr-x    3 root     root        4.0K Nov 10 17:34 .
drwxr-xr-x    1 root     root        4.0K Nov 10 17:34 ..
drwxr-xr-x    3 1000     1000        4.0K Oct 26 20:24 .task
-rw-rw-r--    1 1000     1000        2.3K Nov 10 09:08 .taskrc
```
I think after this I'll just let it go, if you don't have any hints. Thanks for the effort, though.

**Comment by DCsunset** [comment]
No. What I mean is that you need to set the env variables for the container itself. In your case, the docker-compose.yml should be like this:

```yml
version: '3.7'
services:
  taskwarrior-webui:
    image: dcsunset/taskwarrior-webui:latest
    container_name: taskwarrior-webui
    enviroment:
      - TASKRC=/home/username/.taskrc
      - TASKDATA=/home/username/.task
    volumes:
      - /home/username/.taskrc:/home/username/.taskrc
      - /home/username/.task:/home/username/.task
    ports:
      - 5678:80
    restart: always
```

If you don't set those env variables, the container is not able to know the `/home/username` because its user should `root`.
