### ISSUE TITLE
Fails to fetch data when taskrc has a theme include directive

### ISSUE THREAD

**Issue by myukselen** [DCsunset/taskwarrior-webui#59]
Hi,

I have just enabled a theme in `.taskrc` file and can not get any task data.

I think there is a missing documentation piece at least for my usecase. 
The theme file is in `/usr/local/Cellar/task/2.6.2/share/doc/task/rc` folder.

Thanks,
-Murat

**Comment by DCsunset** [comment]
Are you using the Docker container? If so, I think it's probably because you didn't mount the file into the container.

**Comment by myukselen** [comment]
Yes I am using Docker.

The include line is like this in `.taskrc`:
```
include solarized-dark-256.theme
```

Where should I map the `/usr/local/Cellar/task/2.6.2/share/doc/task/rc` folder so that it can used? 
I don't know which additional folders are being checked

**Comment by DCsunset** [comment]
I'm not familiar with the include command so I may not be of great help. You can check the official document of taskwarrior. Besides, an easy way to debug it is to run the `task` command inside the container to see the error message.

**Comment by Paraidomat** [comment]
Hi @myukselen 

may I ask what you are trying to achieve? 
If you want to change the colorscheme of the website the include of the .taskrc isn't of any help.

You'd need to fiddle with the css of the website.

**Comment by myukselen** [comment]
You can consider this as a bug. I wanted to use the dockerized application and followed the instructions. Issue subject line is a concise description.

I don't expect any behavior changes related to theme files or values.

**Comment by bitroniq** [comment]
I have the same issue.

I made a `docker-compose.yml` and run the app

```
❯ cat docker-compose.yml
version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 5679:80
    deploy:
      restart_policy:
        condition: always
    volumes:
    - ~/.taskrc:/.taskrc
    - ~/.task:/.task
 ```

The problem is that no tasks are visible on the page

![image](https://github.com/DCsunset/taskwarrior-webui/assets/1032724/f26145c7-5636-43d5-89b5-1c97f2443c19)


And in the logs I see

![image](https://github.com/DCsunset/taskwarrior-webui/assets/1032724/87e1e7c6-0034-44bc-a557-0e8e0d4d2c5f)
